#ifndef CNET_GAMED_GSP_IF_H
#define CNET_GAMED_GSP_IF_H

namespace GMSV
{
    enum
    {
        CHAT_CHANNEL_LOCAL = 0,
        CHAT_CHANNEL_FARCRY,
        CHAT_CHANNEL_TEAM,
        CHAT_CHANNEL_FACTION ,
        CHAT_CHANNEL_WHISPER ,
        CHAT_CHANNEL_DAMAGE,
        CHAT_CHANNEL_FIGHT,
        CHAT_CHANNEL_TRADE,
        CHAT_CHANNEL_SYSTEM,
        CHAT_CHANNEL_BROADCAST,
        CHAT_CHANNEL_MISC,
        CHAT_CHANNEL_INSTANCE,
        CHAT_CHANNEL_SUPERFARCRY,
        CHAT_CHANNEL_BATTLE,
        CHAT_CHANNEL_COUNTRY,
    };
}

#endif // CNET_GAMED_GSP_IF_H